CourseWork.Web/Controllers/AdminController.cs
using System.Threading.Tasks;
using CourseWork.Business.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace CourseWork.Web.Controllers
{
    [Authorize(Roles = "admin")]
    public class AdminController : Controller
    {
        private IAdminService _adminService;

        public AdminController(IAdminService adminService)
        {
            _adminService = adminService;
        }

        [Route("/UserAdmin")]
        public async Task<IActionResult> Index(int page = 1)
        {
            Response.Cookies.Append("adminPage", page.ToString());
            return View(await _adminService.GetUsers(User));
        }

        public async Task<IActionResult> AddAdmin(string userId)
        {
            await _adminService.AddAdmin(userId);
            return RedirectToAction("Index");
        }
        
        public async Task<IActionResult> Block(string userId)
        {
            await _adminService.BlockUser(userId);
            return RedirectToAction("Index");
        }
        
        public async Task<IActionResult> Delete(string userId)
        {
            await _adminService.DeleteUser(userId);
            return RedirectToAction("Index");
        }
        
        
    }
}

CourseWork.Web/Controllers/CollectionController.cs
using System.Collections.Generic;
using System.Threading.Tasks;
using CourseWork.Business.Dto;
using CourseWork.Business.Interfaces;
using CourseWork.Business.Utils;
using CourseWork.Web.ViewModels;
using HeyRed.MarkdownSharp;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace CourseWork.Web.Controllers
{
    [Authorize]
    public class CollectionController : Controller
    {
        private readonly ICollectionService _collectionService;

        public CollectionController(ICollectionService collectionService)
        {
            _collectionService = collectionService;
        }
        
        [Route("/Collections", Name = "Profile")]
        public async Task<IActionResult> Index(
            [FromQuery] int page = 1,
            [FromQuery] string userId = "")
        {
            var collections = await _collectionService.GetUserCollections(User, page, userId);
            
            var markdown = new Markdown();
            
            foreach(var entity in collections.Entities)
            {
                entity.Description = markdown.Transform(entity.Description);
            }
            
            ViewData["userId"] = userId;
            Response.Cookies.Append("collectionPage", page.ToString());
            
            return View(collections);
        }

        [HttpGet]
        public IActionResult Create([FromQuery] string userId = "")
        {
            Response.Cookies.Delete("collectionId");
            ViewData["userId"] = userId;
            return View("Form", new CollectionViewModel
            {
                Topics = _collectionService.GetTopics()
            });
        }

        [HttpPost]
        public async Task<IActionResult> Create(CollectionViewModel collectionViewModel, [FromQuery] string userId = "")
        {
            await _collectionService.CreateCollection(
                User,
                MapperUtil.Map<CollectionViewModel, CollectionDto>(collectionViewModel),
                userId
                );
            return RedirectToAction("Index", new { userId = userId});
        }

        [HttpGet("/Collection/Edit")]
        public async Task<IActionResult> Edit([FromQuery(Name = "collectionId")] int collectionId,
            [FromQuery] string userId = "")
        {
            try
            {
                var collectionDto = await _collectionService.GetCollection(collectionId);
                
                Response.Cookies.Append("collectionId",collectionId.ToString());
                
                var collection = MapperUtil.Map<CollectionDto, CollectionViewModel>(collectionDto);
                
                await _collectionService.CheckRights(User, collectionId);
                
                ViewData["userId"] = userId;
                
                return View("Form", collection);
            }
            catch
            {
                return NotFound();
            }   
        }
        
        [HttpPost]
        public async Task<IActionResult> Edit(
            CollectionViewModel collectionViewModel, 
            [FromQuery(Name = "collectionId")] int collectionId, 
            [FromQuery] string userId = "")
        {
            try
            {
                collectionViewModel.Id = collectionId;
                await _collectionService.EditCollection(
                    MapperUtil.Map<CollectionViewModel, CollectionDto>(collectionViewModel),
                    User
                );
                return RedirectToAction("Index", new { userId = userId });
            }
            catch
            {
                return NotFound();
            }
        }

        [HttpPost]
        public async Task<IActionResult> Delete([FromQuery] int collectionId, [FromQuery] string userId = "")
        {
            try
            {
                await _collectionService.DeleteCollection(collectionId, User);
                return RedirectToAction("Index", new { userId = userId });
            }
            catch
            {
                return NotFound();
            }
        }

        [Route("/Collections/{collectionId}/Images")]
        public IEnumerable<string> GetImages(int collectionId)
        {
            return _collectionService.GetImages(collectionId);
        }
    }
}

CourseWork.Web/Views/Admin/Index.cshtml
@using Microsoft.AspNetCore.Mvc.Localization
@model IEnumerable<CourseWork.Domain.Models.User>

@inject IViewLocalizer Localizer

@{
    Layout = "_Layout";
}

<div class="table-responsive">
    <table class="table mt-2">
        <thead>
            <tr class="d-flex">
                <th class="col-5">@Localizer["Username"]</th>
                <th class="col-5">@Localizer["Email"]</th>
                <th class="col-2"></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var user in @Model)
            {
                <tr class="d-flex @(user.LockoutEnabled ? "table-danger": "")" 
                    title="@(user.LockoutEnabled ? "Blocked": "")">
                    <td class="col-5 text-break">
                        <a asp-controller="Collection"
                           asp-action="Index"
                           asp-route-userId="@user.Id">
                            @user.UserName
                        </a>
                    </td>
                    <td class="col-5 text-break">@user.Email</td>
                    <td class="col-2">
                        <form asp-controller="Admin"
                                asp-action="AddAdmin"
                                asp-route-userId="@user.Id"
                                class="d-inline">
                            <button class="btn btn-success btn-sm m-1"
                                    type="submit"
                                    title="@Localizer["AddAdmin"]">
                                <i class="bi bi-star-fill"></i>
                            </button>
                        </form>
                        <form asp-controller="Admin"
                                asp-action="Block"
                                asp-route-userId="@user.Id"
                                class="d-inline">
                            <button class="btn btn-warning btn-sm m-1"
                                    type="submit"
                                    title="@Localizer["Block"]">
                                <i class="bi bi-lock-fill"></i>
                            </button>
                        </form>
                        <form asp-controller="Admin"
                                asp-action="Delete"
                                asp-route-userId="@user.Id"
                                class="d-inline">
                            <button class="btn btn-danger btn-sm m-1 delete-btn"
                                    type="submit"
                                    title="@Localizer["Delete"]">
                                <i class="bi bi-trash3"></i>
                            </button>
                        </form>
                    </td>
                </tr>
                }
        </tbody>
    </table>
</div>

<script src="~/js/profile.js"></script>